// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Purrrfect_Cats.Data;

#nullable disable

namespace Purrrfect_Cats.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230509151634_NewInitialMigration")]
    partial class NewInitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FavoriteCatsHashtag", b =>
                {
                    b.Property<int>("FavoriteCatsId")
                        .HasColumnType("int");

                    b.Property<int>("HashtagsId")
                        .HasColumnType("int");

                    b.HasKey("FavoriteCatsId", "HashtagsId");

                    b.HasIndex("HashtagsId");

                    b.ToTable("CatTags", (string)null);
                });

            modelBuilder.Entity("Purrrfect_Cats.Models.FavoriteCats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BreedName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FavoriteCats");
                });

            modelBuilder.Entity("Purrrfect_Cats.Models.Hashtag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Hashtags");
                });

            modelBuilder.Entity("FavoriteCatsHashtag", b =>
                {
                    b.HasOne("Purrrfect_Cats.Models.FavoriteCats", null)
                        .WithMany()
                        .HasForeignKey("FavoriteCatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Purrrfect_Cats.Models.Hashtag", null)
                        .WithMany()
                        .HasForeignKey("HashtagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
